const db = require('../config/db');

// 1. Get All Products (For the Storefront)
exports.getAllProducts = async (req, res) => {
  try {
    const result = await db.query(
      'SELECT p.*, c.name as category_name FROM products p JOIN categories c ON p.category_id = c.category_id WHERE is_available = true'
    );
    res.status(200).json({ status: 'success', data: result.rows });
  } catch (error) {
    res.status(500).json({ message: "Error fetching products" });
  }
};

// 2. Create Product (Admin Only)
exports.createProduct = async (req, res) => {
  const { name, category_id, description, price, stock_quantity } = req.body;
  
  // The URL generated by Cloudinary
  const image_url = req.file ? req.file.path : 'https://via.placeholder.com/300';

  try {
    const query = `
      INSERT INTO products (name, category_id, description, price, stock_quantity, image_url)
      VALUES ($1, $2, $3, $4, $5, $6)
      RETURNING *;
    `;
    const result = await db.query(query, [name, category_id, description, price, stock_quantity, image_url]);

    res.status(201).json({ status: 'success', data: result.rows[0] });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Error creating product" });
  }
};